services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: queueforge
      POSTGRES_PASSWORD: queueforge
      POSTGRES_DB: queueforge
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U queueforge -d queueforge"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:8.10-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"


volumes:
  postgres_data:
  redis_data: